tap 'caskroom/cask'

cask 'appcleaner' 
cask 'vivaldi' 
cask 'iterm2'

cask 'visual-studio-code' 
brew 'neovim' 


brew 'zsh'
brew 'git' 
brew 'tree' 
brew 'rmtrash' 
brew 'fzf' 

cask 'alfred'

brew 'chunkwm' 
cask 'karabiner-elements' 

cask 'docker' 

