# Git
abbrev-alias gst="git status"
abbrev-alias gss="git stash"
# %an: autor
# %C: 次の要素のみため(<color>, bold, reverseなど)指定
abbrev-alias glo='git log --graph --color=always --format="%C(magenta)%an% C(auto)%h%d %s %C(black)%C(bold)%cr"'
abbrev-alias ga="git add"
abbrev-alias gaa="git add -A"
abbrev-alias gbr="git branch"
abbrev-alias gf="git fetch"
abbrev-alias gdf="git diff"
abbrev-alias gdn="git diff --name-only"
abbrev-alias gca="git commit -a -m"
abbrev-alias gcm="git commit -m"
abbrev-alias gpk="git cherry-pick"
abbrev-alias gpc="git cherry-pick --continue"
abbrev-alias gpa="git cherry-pick --abort"
abbrev-alias grb="git rebase"
abbrev-alias gri="git rebase -i"
abbrev-alias grc="git rebase --continue"
abbrev-alias gra="git rebase --abort"
abbrev-alias gpo="git push origin"
abbrev-alias gpl="git pull"
abbrev-alias gam="git commit --amend"
abbrev-alias gch="git checkout"
abbrev-alias gsw="git switch"
abbrev-alias grs="git restore"
