[[plugins]] 
repo = 'tpope/vim-surround'

[[plugins]] 
repo = 'Shougo/deoplete.nvim'
hook_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]] 
repo = 'Shougo/denite.nvim' 
hook_add = 'source ~/.config/nvim/keymap/plugin/denite.vim'
[[plugins]] 
repo = 'easymotion/vim-easymotion' 
hook_add = 'source ~/.config/nvim/keymap/plugin/easymotion.vim' 

[[plugins]] 
repo = 'haya14busa/vim-edgemotion'
hook_add = 'source ~/.config/nvim/keymap/plugin/edgemotion.vim' 

[[plugins]] 
repo = 'cespare/vim-toml' 

[[plugins]] 
repo = 'Shougo/neomru.vim' 
[[plugins]] 
repo = 'Shougo/neoyank.vim' 

[[plugins]] 
repo = 'Shougo/defx.nvim' 
hook_add = 'source ~/.config/nvim/keymap/plugin/defx.vim'

[[plugins]] 
repo = 'osyo-manga/vim-over'

[[plugins]] 
repo = 'hotwatermorning/auto-git-diff'

[[plugins]] 
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]] 
repo = 'sainnhe/gruvbox-material'


