tap 'homebrew/cask'

cask 'appcleaner' 
cask 'iterm2'
cask 'copyq'
cask 'google-japanese-ime'

cask 'visual-studio-code' 
brew 'neovim' 

brew 'zsh'
brew 'git' 
brew 'tree' 
brew 'rmtrash' 
brew 'colordiff' 
brew 'ranger' 
brew 'tmux' 
brew 'fzy' 
brew 'autojump' 
brew 'the_silver_searcher' 

tap 'koekeishiya/formulae'
brew 'chunkwm' 

cask 'docker' 
